// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(hush_syncFFI)
import hush_syncFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_hush_sync_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_hush_sync_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A connected hush-sync session over TCP.
 *
 * Create via `HushFfiSession.create(...)`.  All key arguments are raw bytes.
 */
public protocol HushFfiSessionProtocol : AnyObject {
    
    /**
     * Admit a pending member identified by their opaque `token` from `onMemberRequest`.
     *
     * Returns `true` if admitted, `false` if the token is unknown or the pairing window closed.
     */
    func acceptMember(token: String)  -> Bool
    
    /**
     * Close the pairing window without admitting any device.
     */
    func cancelPairing() 
    
    /**
     * Destroy the group: push Revoke to all members, wipe local state, fire on_group_destroyed.
     * Session becomes terminal — all subsequent `send()` calls return `GroupDestroyed`.
     */
    func destroyGroup() 
    
    /**
     * Join a group as the responding device by decoding the initiator's `token`
     * and sending a `Pair` message with this device's public keys.
     * Returns `SessionError::InvalidToken` if the token is malformed.
     */
    func joinGroup(token: String) throws 
    
    /**
     * Auto-generated display name for the local device.
     * Derived from the local signing public key — identical to the `name`
     * field this device would have in a remote device's `members()` list.
     */
    func localDeviceName()  -> String
    
    /**
     * Stable opaque identifier for the local device.
     * Derived from the local signing public key — identical to the `id`
     * field this device would have in a remote device's `members()` list.
     */
    func localNodeId()  -> String
    
    /**
     * List remote group members (excludes the local device).
     *
     * Returns an empty `Vec` when no manifest is set.
     * Each `Member` has a stable `id` and an auto-generated `name`.
     */
    func members()  -> [Member]
    
    /**
     * Opens a pairing window and returns an opaque base64url token.
     * The window stays open until either `acceptMember()` is called (single-use:
     * the window closes after the first accept) or the caller explicitly calls
     * `cancelPairing()`. There is no auto-expiry — the caller controls lifetime
     * by closing the pairing UI and calling `cancelPairing()` on dismiss (ADR-0021).
     * The token encodes `noise_pub || signing_pub || device_name` — pass it to
     * the peer's `joinGroup(token)` call.
     */
    func pairingToken()  -> String
    
    /**
     * Remove a group member by their opaque `member_id` from `members()`.
     *
     * Issues a new manifest excluding the target and propagates it to all
     * remaining members (including the removed device so it can fire
     * `onRemovedFromGroup`).
     *
     * Returns `SessionError::NotInGroup` if no manifest is set.
     * Returns `SessionError::MemberNotFound` if no member with that id exists.
     */
    func removeMember(memberId: String) throws 
    
    /**
     * Encrypt `blob` and fan out to all current group members.
     * Returns `SessionError::NotInGroup` if the session has no manifest yet.
     */
    func send(blob: Data) throws 
    
    /**
     * Register the callback fired when a new member joins the group.
     *
     * Fires both on the admitting device (after `acceptMember`) and on all other
     * current members when they receive the updated manifest.
     */
    func setOnMemberJoined(callback: MemberJoinedCallback) 
    
    /**
     * Register the callback fired when a member is removed from the group (Soft Removal).
     *
     * Does NOT fire when the local device is removed — that fires `onRemovedFromGroup`.
     */
    func setOnMemberLeft(callback: MemberLeftCallback) 
    
    /**
     * Register the callback fired when a `Pair` message arrives within an open pairing window.
     *
     * `callback.on_member_request(token, name)` fires with the opaque request token
     * and the auto-generated member name. Pass `token` to `accept_member(token)` to admit.
     */
    func setOnMemberRequest(callback: MemberRequestCallback) 
    
}

/**
 * A connected hush-sync session over TCP.
 *
 * Create via `HushFfiSession.create(...)`.  All key arguments are raw bytes.
 */
open class HushFfiSession:
    HushFfiSessionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_hush_sync_fn_clone_hushffisession(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_hush_sync_fn_free_hushffisession(pointer, $0) }
    }

    
    /**
     * Create a session. Always succeeds — the relay connects in the background.
     *
     * - `base_dir`: directory where the SQLite database is stored
     * - `namespace`: scopes the database file; one session per namespace
     * - `relay_host`: relay hostname or IP, e.g. `"relay.example.com"` (no port — ports are managed internally)
     * - `relay_pub`: 32-byte X25519 relay public key (wrong length → `InvalidRelayPublicKey`)
     * - `on_message`: called for every inbound `Sync` message
     *
     * The identity keypair is loaded from SQLite or auto-generated on first launch.
     * Automatically reconnects on relay disconnects using an exponential backoff
     * capped at 30 seconds.
     */
public static func create(baseDir: String, namespace: String, relayHost: String, relayPub: Data, onMessage: MessageCallback, onRemovedFromGroup: RemovedFromGroupCallback, onGroupDestroyed: GroupDestroyedCallback, onConnectionChanged: ConnectionChangedCallback?)throws  -> HushFfiSession {
    return try  FfiConverterTypeHushFfiSession.lift(try rustCallWithError(FfiConverterTypeSessionError.lift) {
    uniffi_hush_sync_fn_constructor_hushffisession_create(
        FfiConverterString.lower(baseDir),
        FfiConverterString.lower(namespace),
        FfiConverterString.lower(relayHost),
        FfiConverterData.lower(relayPub),
        FfiConverterCallbackInterfaceMessageCallback.lower(onMessage),
        FfiConverterCallbackInterfaceRemovedFromGroupCallback.lower(onRemovedFromGroup),
        FfiConverterCallbackInterfaceGroupDestroyedCallback.lower(onGroupDestroyed),
        FfiConverterOptionCallbackInterfaceConnectionChangedCallback.lower(onConnectionChanged),$0
    )
})
}
    

    
    /**
     * Admit a pending member identified by their opaque `token` from `onMemberRequest`.
     *
     * Returns `true` if admitted, `false` if the token is unknown or the pairing window closed.
     */
open func acceptMember(token: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_accept_member(self.uniffiClonePointer(),
        FfiConverterString.lower(token),$0
    )
})
}
    
    /**
     * Close the pairing window without admitting any device.
     */
open func cancelPairing() {try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_cancel_pairing(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Destroy the group: push Revoke to all members, wipe local state, fire on_group_destroyed.
     * Session becomes terminal — all subsequent `send()` calls return `GroupDestroyed`.
     */
open func destroyGroup() {try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_destroy_group(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Join a group as the responding device by decoding the initiator's `token`
     * and sending a `Pair` message with this device's public keys.
     * Returns `SessionError::InvalidToken` if the token is malformed.
     */
open func joinGroup(token: String)throws  {try rustCallWithError(FfiConverterTypeSessionError.lift) {
    uniffi_hush_sync_fn_method_hushffisession_join_group(self.uniffiClonePointer(),
        FfiConverterString.lower(token),$0
    )
}
}
    
    /**
     * Auto-generated display name for the local device.
     * Derived from the local signing public key — identical to the `name`
     * field this device would have in a remote device's `members()` list.
     */
open func localDeviceName() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_local_device_name(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Stable opaque identifier for the local device.
     * Derived from the local signing public key — identical to the `id`
     * field this device would have in a remote device's `members()` list.
     */
open func localNodeId() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_local_node_id(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * List remote group members (excludes the local device).
     *
     * Returns an empty `Vec` when no manifest is set.
     * Each `Member` has a stable `id` and an auto-generated `name`.
     */
open func members() -> [Member] {
    return try!  FfiConverterSequenceTypeMember.lift(try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_members(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Opens a pairing window and returns an opaque base64url token.
     * The window stays open until either `acceptMember()` is called (single-use:
     * the window closes after the first accept) or the caller explicitly calls
     * `cancelPairing()`. There is no auto-expiry — the caller controls lifetime
     * by closing the pairing UI and calling `cancelPairing()` on dismiss (ADR-0021).
     * The token encodes `noise_pub || signing_pub || device_name` — pass it to
     * the peer's `joinGroup(token)` call.
     */
open func pairingToken() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_pairing_token(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Remove a group member by their opaque `member_id` from `members()`.
     *
     * Issues a new manifest excluding the target and propagates it to all
     * remaining members (including the removed device so it can fire
     * `onRemovedFromGroup`).
     *
     * Returns `SessionError::NotInGroup` if no manifest is set.
     * Returns `SessionError::MemberNotFound` if no member with that id exists.
     */
open func removeMember(memberId: String)throws  {try rustCallWithError(FfiConverterTypeSessionError.lift) {
    uniffi_hush_sync_fn_method_hushffisession_remove_member(self.uniffiClonePointer(),
        FfiConverterString.lower(memberId),$0
    )
}
}
    
    /**
     * Encrypt `blob` and fan out to all current group members.
     * Returns `SessionError::NotInGroup` if the session has no manifest yet.
     */
open func send(blob: Data)throws  {try rustCallWithError(FfiConverterTypeSessionError.lift) {
    uniffi_hush_sync_fn_method_hushffisession_send(self.uniffiClonePointer(),
        FfiConverterData.lower(blob),$0
    )
}
}
    
    /**
     * Register the callback fired when a new member joins the group.
     *
     * Fires both on the admitting device (after `acceptMember`) and on all other
     * current members when they receive the updated manifest.
     */
open func setOnMemberJoined(callback: MemberJoinedCallback) {try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_set_on_member_joined(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceMemberJoinedCallback.lower(callback),$0
    )
}
}
    
    /**
     * Register the callback fired when a member is removed from the group (Soft Removal).
     *
     * Does NOT fire when the local device is removed — that fires `onRemovedFromGroup`.
     */
open func setOnMemberLeft(callback: MemberLeftCallback) {try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_set_on_member_left(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceMemberLeftCallback.lower(callback),$0
    )
}
}
    
    /**
     * Register the callback fired when a `Pair` message arrives within an open pairing window.
     *
     * `callback.on_member_request(token, name)` fires with the opaque request token
     * and the auto-generated member name. Pass `token` to `accept_member(token)` to admit.
     */
open func setOnMemberRequest(callback: MemberRequestCallback) {try! rustCall() {
    uniffi_hush_sync_fn_method_hushffisession_set_on_member_request(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceMemberRequestCallback.lower(callback),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHushFfiSession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = HushFfiSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> HushFfiSession {
        return HushFfiSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: HushFfiSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HushFfiSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: HushFfiSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHushFfiSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> HushFfiSession {
    return try FfiConverterTypeHushFfiSession.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHushFfiSession_lower(_ value: HushFfiSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeHushFfiSession.lower(value)
}


/**
 * A remote group member as seen through the FFI surface.
 */
public struct Member {
    /**
     * Stable opaque identifier, e.g. `"YWJjZGVmZ2"`.
     */
    public var id: String
    /**
     * Auto-generated human-readable name, e.g. `"AmberFalcon"`.
     */
    public var name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable opaque identifier, e.g. `"YWJjZGVmZ2"`.
         */id: String, 
        /**
         * Auto-generated human-readable name, e.g. `"AmberFalcon"`.
         */name: String) {
        self.id = id
        self.name = name
    }
}



extension Member: Equatable, Hashable {
    public static func ==(lhs: Member, rhs: Member) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMember: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Member {
        return
            try Member(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Member, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMember_lift(_ buf: RustBuffer) throws -> Member {
    return try FfiConverterTypeMember.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMember_lower(_ value: Member) -> RustBuffer {
    return FfiConverterTypeMember.lower(value)
}


public enum SessionError {

    
    
    case InvalidKeyLength(expected: UInt32, got: UInt32
    )
    case InvalidRelayPublicKey
    case InvalidNamespace(msg: String
    )
    case PushFailed(msg: String
    )
    case InvalidToken
    case NotInGroup
    case MemberNotFound
    case GroupDestroyed
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionError: FfiConverterRustBuffer {
    typealias SwiftType = SessionError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidKeyLength(
            expected: try FfiConverterUInt32.read(from: &buf), 
            got: try FfiConverterUInt32.read(from: &buf)
            )
        case 2: return .InvalidRelayPublicKey
        case 3: return .InvalidNamespace(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .PushFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidToken
        case 6: return .NotInGroup
        case 7: return .MemberNotFound
        case 8: return .GroupDestroyed

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SessionError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidKeyLength(expected,got):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(expected, into: &buf)
            FfiConverterUInt32.write(got, into: &buf)
            
        
        case .InvalidRelayPublicKey:
            writeInt(&buf, Int32(2))
        
        
        case let .InvalidNamespace(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .PushFailed(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .InvalidToken:
            writeInt(&buf, Int32(5))
        
        
        case .NotInGroup:
            writeInt(&buf, Int32(6))
        
        
        case .MemberNotFound:
            writeInt(&buf, Int32(7))
        
        
        case .GroupDestroyed:
            writeInt(&buf, Int32(8))
        
        }
    }
}


extension SessionError: Equatable, Hashable {}

extension SessionError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




/**
 * Fired when the relay connection state changes.
 * `connected = true` when the relay connects; `false` when it disconnects.
 * Informational only — the library queues outbox messages and reconnects automatically.
 * Does NOT fire at session construction time.
 */
public protocol ConnectionChangedCallback : AnyObject {
    
    func onConnectionChanged(connected: Bool) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceConnectionChangedCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceConnectionChangedCallback = UniffiVTableCallbackInterfaceConnectionChangedCallback(
        onConnectionChanged: { (
            uniffiHandle: UInt64,
            connected: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceConnectionChangedCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onConnectionChanged(
                     connected: try FfiConverterBool.lift(connected)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceConnectionChangedCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface ConnectionChangedCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitConnectionChangedCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_connectionchangedcallback(&UniffiCallbackInterfaceConnectionChangedCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceConnectionChangedCallback {
    fileprivate static var handleMap = UniffiHandleMap<ConnectionChangedCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceConnectionChangedCallback : FfiConverter {
    typealias SwiftType = ConnectionChangedCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * After this fires the session is terminal; call `create()` on the same namespace
 * to start fresh with a new identity.
 */
public protocol GroupDestroyedCallback : AnyObject {
    
    func onGroupDestroyed() 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceGroupDestroyedCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceGroupDestroyedCallback = UniffiVTableCallbackInterfaceGroupDestroyedCallback(
        onGroupDestroyed: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceGroupDestroyedCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onGroupDestroyed(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceGroupDestroyedCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface GroupDestroyedCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitGroupDestroyedCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_groupdestroyedcallback(&UniffiCallbackInterfaceGroupDestroyedCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceGroupDestroyedCallback {
    fileprivate static var handleMap = UniffiHandleMap<GroupDestroyedCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceGroupDestroyedCallback : FfiConverter {
    typealias SwiftType = GroupDestroyedCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Fired when a new member appears in an incoming manifest update or after `acceptMember` succeeds.
 */
public protocol MemberJoinedCallback : AnyObject {
    
    func onMemberJoined(memberId: String, memberName: String) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceMemberJoinedCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceMemberJoinedCallback = UniffiVTableCallbackInterfaceMemberJoinedCallback(
        onMemberJoined: { (
            uniffiHandle: UInt64,
            memberId: RustBuffer,
            memberName: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMemberJoinedCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMemberJoined(
                     memberId: try FfiConverterString.lift(memberId),
                     memberName: try FfiConverterString.lift(memberName)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceMemberJoinedCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface MemberJoinedCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitMemberJoinedCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_memberjoinedcallback(&UniffiCallbackInterfaceMemberJoinedCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceMemberJoinedCallback {
    fileprivate static var handleMap = UniffiHandleMap<MemberJoinedCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceMemberJoinedCallback : FfiConverter {
    typealias SwiftType = MemberJoinedCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Fired when a member disappears from an incoming manifest update (Soft Removal).
 * Does NOT fire when the local device is the removed one — that fires `onRemovedFromGroup`.
 */
public protocol MemberLeftCallback : AnyObject {
    
    func onMemberLeft(memberId: String, memberName: String) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceMemberLeftCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceMemberLeftCallback = UniffiVTableCallbackInterfaceMemberLeftCallback(
        onMemberLeft: { (
            uniffiHandle: UInt64,
            memberId: RustBuffer,
            memberName: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMemberLeftCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMemberLeft(
                     memberId: try FfiConverterString.lift(memberId),
                     memberName: try FfiConverterString.lift(memberName)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceMemberLeftCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface MemberLeftCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitMemberLeftCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_memberleftcallback(&UniffiCallbackInterfaceMemberLeftCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceMemberLeftCallback {
    fileprivate static var handleMap = UniffiHandleMap<MemberLeftCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceMemberLeftCallback : FfiConverter {
    typealias SwiftType = MemberLeftCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Fired when a `Pair` message arrives within an open pairing window.
 * The caller shows UI ("Name wants to join — Accept?"), then calls
 * `accept_member(token)` or ignores the request.
 */
public protocol MemberRequestCallback : AnyObject {
    
    func onMemberRequest(token: String, name: String) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceMemberRequestCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceMemberRequestCallback = UniffiVTableCallbackInterfaceMemberRequestCallback(
        onMemberRequest: { (
            uniffiHandle: UInt64,
            token: RustBuffer,
            name: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMemberRequestCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMemberRequest(
                     token: try FfiConverterString.lift(token),
                     name: try FfiConverterString.lift(name)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceMemberRequestCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface MemberRequestCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitMemberRequestCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_memberrequestcallback(&UniffiCallbackInterfaceMemberRequestCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceMemberRequestCallback {
    fileprivate static var handleMap = UniffiHandleMap<MemberRequestCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceMemberRequestCallback : FfiConverter {
    typealias SwiftType = MemberRequestCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Fired when a `Sync` message is delivered to this device.
 * `blob` is the raw application payload; `sender_noise_pub` is the sender's 32-byte X25519 key.
 */
public protocol MessageCallback : AnyObject {
    
    func onMessage(blob: Data, senderNoisePub: Data) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceMessageCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceMessageCallback = UniffiVTableCallbackInterfaceMessageCallback(
        onMessage: { (
            uniffiHandle: UInt64,
            blob: RustBuffer,
            senderNoisePub: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceMessageCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessage(
                     blob: try FfiConverterData.lift(blob),
                     senderNoisePub: try FfiConverterData.lift(senderNoisePub)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceMessageCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface MessageCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitMessageCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_messagecallback(&UniffiCallbackInterfaceMessageCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceMessageCallback {
    fileprivate static var handleMap = UniffiHandleMap<MessageCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceMessageCallback : FfiConverter {
    typealias SwiftType = MessageCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




/**
 * Fired when this device is excluded from an incoming `GroupManifest` update.
 * Another group member has issued a Soft Removal of this device (ADR-0015).
 * The session remains connected; the caller decides whether to wipe and re-pair.
 */
public protocol RemovedFromGroupCallback : AnyObject {
    
    func onRemovedFromGroup() 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceRemovedFromGroupCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceRemovedFromGroupCallback = UniffiVTableCallbackInterfaceRemovedFromGroupCallback(
        onRemovedFromGroup: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceRemovedFromGroupCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onRemovedFromGroup(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceRemovedFromGroupCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface RemovedFromGroupCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitRemovedFromGroupCallback() {
    uniffi_hush_sync_fn_init_callback_vtable_removedfromgroupcallback(&UniffiCallbackInterfaceRemovedFromGroupCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceRemovedFromGroupCallback {
    fileprivate static var handleMap = UniffiHandleMap<RemovedFromGroupCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceRemovedFromGroupCallback : FfiConverter {
    typealias SwiftType = RemovedFromGroupCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceConnectionChangedCallback: FfiConverterRustBuffer {
    typealias SwiftType = ConnectionChangedCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceConnectionChangedCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceConnectionChangedCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMember: FfiConverterRustBuffer {
    typealias SwiftType = [Member]

    public static func write(_ value: [Member], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMember.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Member] {
        let len: Int32 = try readInt(&buf)
        var seq = [Member]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMember.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_hush_sync_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_accept_member() != 16777) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_cancel_pairing() != 53746) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_destroy_group() != 1217) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_join_group() != 37308) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_local_device_name() != 59797) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_local_node_id() != 1866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_members() != 20760) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_pairing_token() != 21095) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_remove_member() != 16018) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_send() != 20850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_set_on_member_joined() != 35932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_set_on_member_left() != 50642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_hushffisession_set_on_member_request() != 52552) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_constructor_hushffisession_create() != 32763) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_connectionchangedcallback_on_connection_changed() != 31483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_groupdestroyedcallback_on_group_destroyed() != 37987) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_memberjoinedcallback_on_member_joined() != 2593) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_memberleftcallback_on_member_left() != 26292) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_memberrequestcallback_on_member_request() != 12851) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_messagecallback_on_message() != 64032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_hush_sync_checksum_method_removedfromgroupcallback_on_removed_from_group() != 29262) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitConnectionChangedCallback()
    uniffiCallbackInitGroupDestroyedCallback()
    uniffiCallbackInitMemberJoinedCallback()
    uniffiCallbackInitMemberLeftCallback()
    uniffiCallbackInitMemberRequestCallback()
    uniffiCallbackInitMessageCallback()
    uniffiCallbackInitRemovedFromGroupCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all